# Generated by Django 2.2 on 2019-05-28 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=20)),
                ('courseCredit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('kind', models.CharField(choices=[('teacher', '教师'), ('student', '学生'), ('admin', '管理员')], default='学生', max_length=10)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.User')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.User')),
                ('studentID', models.CharField(max_length=20)),
                ('studentName', models.CharField(max_length=20)),
                ('studentAddress', models.CharField(max_length=128, null=True)),
                ('studentCredit', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.User')),
                ('teacherID', models.CharField(max_length=20)),
                ('teacherName', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score_date', models.IntegerField(null=True)),
                ('scoreCourse', models.CharField(max_length=20, null=True)),
                ('scoreCredit', models.PositiveIntegerField()),
                ('scoreStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Student')),
            ],
        ),
        migrations.CreateModel(
            name='course_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='courseStudent',
            field=models.ManyToManyField(to='system.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseTeacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Teacher'),
        ),
    ]
